### ISSUE TITLE
works on dev, not in production bundle?

### ISSUE THREAD

**Issue by antonybudianto** [brandonroberts/angular2-router-loader#1]
Any specific setting needed to make it work on production bundle?

Repo:
https://github.com/antonybudianto/angular2-starter/tree/feat-webpack-refactor

Try `npm start` and the lazy load worked well.

When `npm run serve-build`, the bundling worked well too, but when trying to click the lazy load menu, the errors thrown:
```
EXCEPTION: Uncaught (in promise): Error: Cannot find module './todolist/todolist.module.ngfactory'.
```

Any clue? Thanks

Using Webpack 2

**Comment by brandonroberts** [comment]
Since AoT is built as a separate step, you have to enable AoT mode for the loader.

`angular2-router-loader?aot=true`

You can add a flag to your webpack config that enables this based on the script you run.

**Comment by antonybudianto** [comment]
```
'angular2-router-loader?loader=system&genDir=aot/src/app&aot=true'
```

```
"angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
```

the bundle still not producing the lazy module chunks

**Comment by brandonroberts** [comment]
Is this still an issue for you? I see you've added some commits to get it working. What I found was that your `todolist/todolist.module` needed to be include in your webpack entries and your tsconfig-aot.json so it gets compiled.

I think you've since updated it to AoT compile into a directory inside of `app`

**Comment by antonybudianto** [comment]
I managed to make it work
https://travis-ci.org/antonybudianto/angular2-starter/jobs/160768231#L1382

please see that the lazy module bundle is 200k, is it normal? the module is small I think, is it because it re-include the `@angular/<module>`? 
Thanks

**Comment by antonybudianto** [comment]
By the way, `0.1.4` and `0.2.0` worked well too

**Comment by brandonroberts** [comment]
I'd say its normal. Webpack is handling the lazy loading and code splitting so it depends on your configuration. AoT produces large compiled files, but they compress really well when gzipped.

**Comment by antonybudianto** [comment]
Okay, thank you!
