### ISSUE TITLE
Route declarations duplicated in AOT output

### ISSUE THREAD

**Issue by benelliott** [brandonroberts/angular2-router-loader#10]
I'm struggling to get the setup right for a lazy-loaded AOT app with Webpack.

Currently my routes are defined in `app/app.routes.ts`, which is imported into my module declaration at `app/app.module.ts`. AOT compilation outputs to the `app/aot` directory. My app is bootstrapped in `app/main.ts`.

The app actually runs fine but compilation produces `Module not found: Error: Can't resolve [route]`. I think the reason for this is that my `app/aot/app.module.ngfactory.ts` has my routes declared inline (autogenerated by the AOT compiler), but since `app/aot/app.module.ngfactory.ts` imports `app/app.module.ts` (import autogenerated by the AOT compiler) which in turn imports `app/aot/app.routes.ts`, I have two versions of the route declarations that end up being passed through the plugin and the relative routes to the modules can only be valid for one of them at any one time.

How do I prevent these duplicated route definitions? Ideally I would only have the top-level, auto-inlined ones. 

Sorry if this is verging on a support question, I tried [asking on StackOverflow](http://stackoverflow.com/questions/39877892/angular-aot-ngc-duplicates-route-definitions) but didn't get a response.

Thanks!

**Comment by brandonroberts** [comment]
Do you have the `genDir` set to the right relative path to your `app` directory? What does your `loaders` section look like?

**Comment by benelliott** [comment]
`genDir` is set to `app/aot` in my `tsconfig.json`, and my loaders look like this:

```
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-router-loader?aot=true&genDir=app/aot', 'angular2-template-loader']
            },
```

**Comment by brandonroberts** [comment]
Its not uncommon that both those files exist after compilation. The `app.routes.ts` gets inlined in `app.module.ngfactory.ts` but its still an import at the top of the file. What would happen ultimately is that `app.routes.ts` would get shaken out of the tree when bundling.

Are you saying that the lazy loading isn't working correctly? If so, can you provide a sample reproduction in a repo?

**Comment by benelliott** [comment]
The lazy loading actually works fine at runtime. It's just that `ngc` duplicates my route definitions, so both sets of definitions are run through `angular2-router-loader` but one is at a different point in the directory tree to the other so the plugin complains for the set of routes that has not been inlined (since the relative path to the lazy-loaded modules cannot resolve correctly from two different points in the file system).

**Comment by brandonroberts** [comment]
The loader should find the relative path from both points in the file system though, so it may be a bug. For ngfactory files, since they are inlined the loader just replaces them as-is. For the non-ngfactory files such as `app.routes.ts` the loader finds the relative path based on the `genDir`.

I initially want to just skip over replacement of the non-ngfactory files when running in AoT mode but it seemed incomplete to do so. If you can reproduce it with this repo that would help https://github.com/brandonroberts/router-loader-test

**Comment by benelliott** [comment]
Thanks, I'll fork it and get back to you.

**Comment by benelliott** [comment]
I think I've found the problem: your repo's `tsconfig.json` has a `genDir` of `./src/compiled` but the value passed to the loader is `src/compiled/src` - i.e. the loader has to be passed the path of the source folder _within your `genDir` folder_ rather than the path of the `genDir` folder itself. Copying this setup for my own app - i.e. setting my loader config from `angular2-router-loader?aot=true&genDir=app/aot` to `angular2-router-loader?aot=true&genDir=app/aot/app` has banished the error messages without breaking the lazy loading. 

This was a user error after all then, but perhaps this could be clarified in the docs for the `genDir` option. I can send a PR if you agree.

Thanks!
