### ISSUE TITLE
loader doesn't do anything

### ISSUE THREAD

**Issue by TylerDev6** [brandonroberts/angular2-router-loader#11]
Not sure what I'm doing wrong, but the loader won't load my route at all. Even turning debug on gives me no output.

const routes: Routes = [
	{ path: '', redirectTo: 'cats', pathMatch: 'full' },
	{ path: 'dogs', loadChildren: './dogs/dog.module#DogModule' }
];

That's my route. Here's my config

{
				test: /\.ts$/,
				loaders: ["awesome-typescript-loader", "angular2-router-loader?debug=true"]
			},

"devDependencies": {
    "angular2-router-loader": "0.3.2",
    "awesome-typescript-loader": "2.2.1",
    "chai": "3.5.0",
    "copy-webpack-plugin": "3.0.1",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "2.0.0-beta.4",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "2.5.2",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-firefox-launcher": "1.0.0",
    "karma-jasmine": "1.0.2",
    "karma-jasmine-matchers": "3.0.1",
    "karma-junit-reporter": "1.1.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "1.8.0",
    "mocha": "3.0.2",
    "node-sass": "3.9.3",
    "protractor": "4.0.9",
    "raw-loader": "^0.5.1",
    "reflect-metadata": "^0.1.3",
    "rimraf": "^2.5.2",
    "sass-loader": "4.0.2",
    "sinon": "1.17.5",
    "source-map-loader": "0.1.5",
    "style-loader": "^0.13.1",
    "ts-loader": "^0.8.1",
    "ts-node": "1.3.0",
    "typescript": "2.0.0",
    "typings": "~1.0.3",
    "webpack": "^2.1.0-beta.25",
    "webpack-dev-server": "2.1.0-beta.8",
    "webpack-merge": "^0.14.0"
  },

**Comment by TylerDev6** [comment]
I've tried multiple versions of webpack, multiple loaders, but nothing happens. the "loadChildren" path remains untouched every time

**Comment by dhardtke** [comment]
Can you post your full webpack config?
(Please use markdown to properly annotate your code, see https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by brandonroberts** [comment]
There is a minimal working repo here you can look at: https://github.com/brandonroberts/router-loader-test

**Comment by TylerDev6** [comment]
Thanks, I'm trying to figure why I'm not even getting error or debug logging, even when setting debug to true... I spent about 3 hours on this so far....

**Comment by TylerDev6** [comment]
I've since reverted to older webpack, here's my full common config
```javascript
var webpack = require("webpack"),
	HtmlWebpackPlugin = require("html-webpack-plugin"),
	ExtractTextPlugin = require("extract-text-webpack-plugin"),
	helpers = require("./helpers");

module.exports = {
	context: helpers.root() + "/src",
	entry: {
		app: "./main.ts",
		vendor: "./../common/vendor.ts",
		polyfills: "./../common/polyfills.ts"
	},
	
	resolve: {
		extensions: ["", ".js", ".ts"]
	},
	
	module: {
		loaders: [
			{
				test: /\.ts$/,
				loaders: ["ts", "angular2-router-loader?debug=true"]
			},
			{
				test: /\.html$/,
				loader: "html"
			},
			{
				test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
				loader: "file?name=assets/[name].[hash].[ext]"
			},
			{
				test: /\.css$/,
				exclude: helpers.root("src", "app"),
				loader: ExtractTextPlugin.extract("style", "css?sourceMap")
			},
			{
				test: /\.css$/,
				include: helpers.root("src", "app"),
				loader: "raw"
			},
			{
				test: /\.s(a|c)ss$/,
				loaders: ["style-loader", "css-loader", "sass-loader"]
			}
		]
	},
	
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			name: ["app", "vendor", "polyfills"]
		}),
		
		new HtmlWebpackPlugin({
			template: "index.html"
		})
	]
}```

**Comment by dhardtke** [comment]
Try this:
https://github.com/brandonroberts/angular2-router-loader/issues/4#issuecomment-250908838

**Comment by TylerDev6** [comment]
thanks dhardtke, that was it!

**Comment by dhardtke** [comment]
Great!

**Comment by TylerDev6** [comment]
problems aside, great library brandon. Maybe this particular gotcha can be called out in the readme?

**Comment by brandonroberts** [comment]
@TylerDev6 yea I need to break up the README into some sections and add a FAQ.
