### ISSUE TITLE
[Question. Not an issue] - Load routes from a config.json file

### ISSUE THREAD

**Issue by jdiapps** [brandonroberts/angular2-router-loader#17]
Does angular2-router-loader allow the dynamic loading of a route at runtime from a configuration file?

Are there any examples of this?

Thanks
Michael

**Comment by brandonroberts** [comment]
This loader does not handle that. Its for splitting up lazy loaded routes into separate bundles at build time.

**Comment by jdiapps** [comment]
How would I handle loading routes from a config file?  Would I have to override the router loader for angular and then do require.ensure()?
