### ISSUE TITLE
Only sync mode seems to work

### ISSUE THREAD

**Issue by patrickarlt** [brandonroberts/angular2-router-loader#18]
I'm trying to integrate lazy loading into a project and I can only seem to get things working by adding `sync=true` to my lazy loaded modules.

```ts
// root.routing.ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
  { path: 'sign-up', loadChildren: './sign-up/sign-up.module#SignUpModule' }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class DevelopersRootRoutingModule { }
```

```ts
// sign-up/sign-up.module.ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { SignUpComponent } from './sign-up.component';

const routes: Routes = [
  { path: '', component: SignUpComponent }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class SignUpRoutingModule { }
```

If I replace the `loadChildren` param on the sign up route with `() => { debugger; }` it does start the debugger so I know that it should be loading the child route. but I see no request in the network panel, but I do see webpack output an extra chunk and the following in `debug`

```
    [angular2-router-loader]: --DEBUG--
    [angular2-router-loader]: File: /Users/patricklocal/code/developers-site/src/assets/js-es6/ng/apps/root.routing.ts
    [angular2-router-loader]: Original: loadChildren: './sign-up/sign-up.module#SignUpModule'
    [angular2-router-loader]: Replacement: loadChildren: () => new Promise(function (resolve) {  (require as any).ensure([], function (require: any) {    resolve(require('./sign-up/sign-up.module')['SignUpModule']);  });})
```

* angular2-router-loader ^0.3.3",
* ts-loader ^0.8.2",
* typescript ^2.0.2",
* webpack ^1.13.2",
* webpack-dev-server ^1.16.2",
* webpack-merge ^0.14.1",
* @angular/common ~2.0.0",
* @angular/compiler ~2.0.0",
* @angular/core ~2.0.0",
* @angular/forms ~2.0.0",
* @angular/http ~2.0.0",
* @angular/platform-browser ~2.0.0",
* @angular/platform-browser-dynamic ~2.0.0",
* @angular/router ~3.0.0",

And I've put a simplified version of my webpack config and tsconfig files in this Gist https://gist.github.com/patrickarlt/46bdf8bc22cb8b459402542a607d4641.

Do you see anything wrong with this configuration? I've tried suggestions from https://github.com/brandonroberts/angular2-router-loader/issues/4#issuecomment-250908838 and https://github.com/brandonroberts/angular2-router-loader/issues/11 by placing `.ts` first in the resolution order but with no luck.

**Comment by brandonroberts** [comment]
I don't see anything wrong with your configuration. Here is a working test repo you can compare against. https://github.com/brandonroberts/router-loader-test

**Comment by patrickarlt** [comment]
@brandonroberts I figured this out. My setup has me running webpack dev server alongside my application server as per [Combining with an existing server](http://webpack.github.io/docs/webpack-dev-server.html#combining-with-an-existing-server) and my `output.publicPath` didn't have a trailing `/`.

Everything works as expected now. Sorry for the time waste, and thanks for an excellent project.

**Comment by brandonroberts** [comment]
Thanks! Glad you got it worked out
