### ISSUE TITLE
Preprocessing commented code

### ISSUE THREAD

**Issue by arcocg** [brandonroberts/angular2-router-loader#2]
Hello.

Plugin modificates commented code.

[Here is array with rotes in code](http://www.scrabber.net/iSVcG.jpg).
[And here is compiled  one](http://www.scrabber.net/6rcPi.jpg).

Block of commented code was compiled and caused an error.

**Comment by brandonroberts** [comment]
Yea, the regex is greedy in that sense. You can work around it by using `loadChildren :` in your comment. I'll work on a better solution for ignoring those types of scenarios

**Comment by IAMtheIAM** [comment]
I had the same issue which was very hard to diagnose. 

```
{
   path: 'detail',
   // loadChildren: () => System.import('../+detail/detail.module'),
   loadChildren: '../+detail/detail.module#DetailModule',
   // loadChildren: 'es6-promise?,[name]!../+detail/detail.module#DetailModule',
   // loadChildren: loadLazy('../+detail/detail.detailRoutes', DetailComponent)
   // loadChildren: () => System.import('../+detail/detail.module.ts')
},
``` 
gave dozens of typescript errors, none of them says "don't use comments in the routes object". That is what it should say.

just changing it to this fixes it:
```
   {
      path: 'detail',
      loadChildren: '../+detail/detail.module#DetailModule',
   },
```
Additionally, I had to use `angular2-router-loader?loader=system` to get it to succeed once I removed the comments, since I'm using webpack 2.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/brandonroberts/angular2-router-loader/commit/6a8285d1b358a62a9035f2b5d0e5f92b9e455674

I updated the regex to be less greedy when matching and also changed the replacement string to be inlined as a single line, so if it does replace a commented string, it won't cause breakage

I also added a `debug` option to log out the matches and replacements during the build.
