### ISSUE TITLE
Hi I have problem with lazy loading. 

### ISSUE THREAD

**Issue by tonimitrevski** [brandonroberts/angular2-router-loader#20]
I use webpack with gulp on laravel and 
![screenshot from 2016-10-22 21-08-53](https://cloud.githubusercontent.com/assets/15773773/19621861/eb6f5736-989b-11e6-9360-ae70d54d5160.png)

what is the problem?

**Comment by brandonroberts** [comment]
That's not enough information for me to help you with. Most likely you're server isn't configured correctly to return your `index.html` instead of a 404 page.

**Comment by tonimitrevski** [comment]
The problem is for when I put on a tag with lazy loading 1.1.js script must be in root folder. Can I configure to read in specific folder (public/js) ?

**Comment by brandonroberts** [comment]
Ideally if you're using webpack to bundle everything up, its going to create the correct references when trying to lazy load. Do you have a repo to share?

**Comment by jbeckton** [comment]
I was wondering if it's possible to tell the loader where to create the chunk file? My webpack config puts all my bundled js code in /js folder but the lasy loaded chunks are created in the root. My app works but I would like the folder structure to be more consistent .

**Comment by brandonroberts** [comment]
Sounds like an issue with your configuration. This loader doesn't control where the chunks generated. They should be all in the same place though.

**Comment by spock123** [comment]
@jbeckton  
Did you make sure to add the correct url params to the loader?
What does your tsconfig.json look like?

I often find that you will need to insert references to the module files of the lazy loaded modules into tsconfig.json

Your error indicates that you got the index.html returned from your webserver.

How to you serve the pages?
What does your setup look like?

FWIW it works beautifully with my setup:

Angular 2.1.1
Webpack 2.1.0-beta.22
Node 6.6

I serve my pages using a Docker image of NgInx

**Comment by spock123** [comment]
@jbeckton  that is a Webpack configuration:

```
  output  : {
            filename     : '<path-to-assets>/[name].[chunkhash].bundle.js',
            chunkFilename: '<path-to-assets>/[id].[chunkhash].chunk.js'
        },
```

**Comment by jbeckton** [comment]
@spock123  

I am using this project https://github.com/preboot/angular2-webpack .

I have a few tweaks but for the most part that config is intact with my project.

I have not used any url params as they do not seem to be reverent with the exception of the genDir which is for AoT and I am not using that right now.

**Comment by jbeckton** [comment]
I just figured it out...

my output was

    `config.output = isTest ? {} : {
        path         : root('dist'),
        publicPath   : isProd ? '/' : 'http://localhost:8080/',
        filename     : isProd ? 'js/[name].[hash].js' : 'js/[name].js',
        chunkFilename: isProd ? '[id].[hash].chunk.js' : '[id].chunk.js'
     };`

so I fixed the chunkFilename path to prefix js/
