### ISSUE TITLE
Using @ngtools/webpack (loading images)

### ISSUE THREAD

**Issue by inzerceubytovani** [brandonroberts/angular2-router-loader#22]
I am using @ngtools/webpack because awesome-typescript-loader does not process images in angular2 templates (I am using AOT).

My tsconfig:

```
 "angularCompilerOptions": {
   "genDir": "./aot/client", // or just ./aot (discribed in one case bellow)
   "skipMetadataEmit" : true
 }

```
But it does not work well with angular2 -router-loader because of genDir property. @ngtools/webpack AotPlugin has it's own genDir property. When I set it to my app dir - thats client/aot, it's generate build without problems, it's also copy images to build right. But it doesn't replace image paths to new one (they stay same to original path, not to generated images in build assets).

When I don't use angular2-router-loader, images working correctly. Images stop to work when I set genDir in AotPlugin to path `client/aot` -  but without set it, I got this error during webpack compilation:

`/client/aot/client/client/app/+faq/faq.module.ngfactory.ts doesn`t exists

I tried to set genDir property in your loader with `angular2-router-loader?aot=true&genDir=client/aot` but it does not affect on loading - I cant build because duplicate path: 

`....client/aot/client/client/app/+faq/faq.module.ngfactory.ts doesn't exist` - that file exists but in location `client/aot/client/app/+faq/faq.module.ngfactory.ts` - part 'client' is twice there.

I tried also generate aot files direct in aot folder (without client folder) - tsconfig - `"genDir": "./aot"`. But it also generate same error during webpack compilation. My @ngtools/webpack genDir property is to nothing (let it default).

`client/aot/client/client/app/+faq/faq.module.ngfactory.ts doesn't exist`

You can see path duplications  - correct path to factory file should be in this case`client/aot/app/+faq/faq.module.ngfactory.ts`. But In this case I was not able to build it with success - I tried to set @ngtools/webpack genDir to some path but always there were one /client/ part more - thats why I changed in tsconfig from path: './aot' to path './aot/client (with this I finally success webpack, with copying images, but without replace of them in generating app bundle).

**It looks like when @ngtools/webpack is used, param genDir in angular2-router-loader stops to work (maybe because of own @ngtools/webpack genDir attribute property).** When I use awesome-typescript-loader, build complete success - but without images and in comparison with using @ngtools/webpack it does not generate images in build assets folder (that @ngtools/webpack does, it only does not replace path in template).

Thanks for any help, I tried to describe it details and how I tried to fix but without success.

**Comment by inzerceubytovani** [comment]
And just noticed one more bug - with @ngtools/webpack template loader generate two some chunks for module istead of one like awesome-typescript-loader. So I just returned to awesome-typescript-loader but when @ngtools/webpack will work with angular2-router-loader I will use it.  Used images in template I copy now like static files with another plugin.

**Comment by brandonroberts** [comment]
@inzerceubytovani this loader isn't mean to be used with the `@ngtools/webpack` plugin because it handles the lazy loaded routes for you.
