### ISSUE TITLE
Wrong path normalized by plugin

### ISSUE THREAD

**Issue by diestrin** [brandonroberts/angular2-router-loader#23]
In my setup I have my components inside node_modules, and webpack knows how to solve a path in any file if I write `require('@company/mycomponent')`.

But when I do the same for the `loadChildren`, it transforms it (and fail) to `./@company/mycomponent`.

Is there a way to avoid the normalized function in your code for it to not include that `./`?

Thanks.

**Comment by brandonroberts** [comment]
@diestrin its a known issue that I'll work on fixing this week.

**Comment by diestrin** [comment]
Cool, actually, if you can share your thoughts on it, I can actually make a PR. Not sure if removing the `./` will have any implications to other people? Or you're thinking on a different strategy?

**Comment by brandonroberts** [comment]
Sure. I'm thinking a simple change would be to check the matched `loadChildren` string. If the original matched string starts with a period, then proceed as if its relative and continue as before with finding the relative path from the root. If it doesn't begin with a period, then don't try to resolve the relative path and proceed as if the module is being resolved from `node_modules` and let webpack handle the resolution.
