### ISSUE TITLE
Absolute path support

### ISSUE THREAD

**Issue by antonybudianto7** [brandonroberts/angular2-router-loader#30]
Hi @brandonroberts 

Recently there is a breaking change from [@ngtools/webpack](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#breaking-changes) that now we must use absolute path for the loadChildren.
I still use the loader when in development.

Thank you

**Comment by brandonroberts** [comment]
Support for absolute paths has already been added via https://github.com/brandonroberts/angular2-router-loader/pull/28 and is in version `0.3.4`

**Comment by antonybudianto7** [comment]
didn't work for me
```ts
{
        path: 'todolist',
        loadChildren: 'app/todolist/todolist.module#TodolistModule'
    }
```
but works with ngtools

**Comment by antonybudianto** [comment]
I see why it didn't worked, because it's resolving from `node_modules`

**Comment by brandonroberts** [comment]
Ok cool @antonybudianto
