### ISSUE TITLE
Doesn't work when routes are defined in separate file

### ISSUE THREAD

**Issue by dhardtke** [brandonroberts/angular2-router-loader#4]
I guess this is intentional, but I think it shouldn't be like this.

These are the entry points I defined in the `webpack.common.js`:
```javascript
entry: {
    "polyfills": "./app/polyfills.ts",
    "vendor":    "./app/vendor.ts",
    "app":       "./app/main.ts"
},
```

I've got my routes defined in a file called `app/app.routes.ts`.

Now if I execute `npm run build` (and btw: I have the aot option set to `true`) it is not working which is due to the fact that the module only gets called for `polyfills.ts`, `vendor.ts` and `main.ts`.

Where is my faulty reasoning?

**Comment by brandonroberts** [comment]
The loader only does replacement for files that pass through the `loaders`. So if your `app.app.routes` doesn't go through your loader for `.ts`, then its not going to pass through this loader either.

**Comment by brandonroberts** [comment]
Routes being defined in a separate file should have no effect either way though

**Comment by dhardtke** [comment]
Thanks for your quick reply.

I do have my routes defined in a TypeScript file. I put a console.log(filename) call in the index.js of your loader to see why the RegEx is not working properly and that made me conclude that it is because filename is only `main.ts`, `vendor.ts` or `polyfills.ts`.

But it should work if the router-loader gets applied after all .ts files get bundled...

**Comment by brandonroberts** [comment]
Are you also restricting your `tsconfig.json` to those 3 files?

**Comment by dhardtke** [comment]
No. There is a `app.routes.js` next to my .ts file.

**Comment by brandonroberts** [comment]
Will you share your `tsconfig.json` and your `loaders` section from your webpack config?

**Comment by dhardtke** [comment]
Of course:
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "strictNullChecks": false,
    "baseUrl": "./app",
    "paths": [
    ],
    "lib": [
      "dom",
      "es5"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```
```javascript
loaders: [
	{
		test:    /\.ts$/,
		loaders: ["awesome-typescript-loader", "angular2-template-loader", "angular2-router-loader?aot=true"]
	},
	/* Raw loader support for *.html
	 * Returns file content as string
	 *
	 * See: https://github.com/webpack/raw-loader
	 */
	{
		test:    /\.html$/,
		loader:  "raw-loader",
		exclude: [helpers.root("app/index.tpl.html")]
	},
	{
		test:   /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
		loader: "file?name=assets/[name].[hash].[ext]"
	},
	{
		test:    /\.css$/,
		exclude: helpers.root("src", "app"),
		loader:  ExtractTextPlugin.extract({fallbackLoader: "style", loader: "css?sourceMap"})
	},
	{
		test:    /\.css$/,
		include: helpers.root("src", "app"),
		loader:  "raw"
	}
]
```

**Comment by dhardtke** [comment]
ping @brandonroberts

**Comment by dhardtke** [comment]
Okay, I think, I figured it out. It's still not working for me but that's another issue related to my asset paths in my Components.

I had to change the order of extensions in `resolve.extensions` so that .ts comes before .js:
`extensions: [".ts", ".js", ".json"],`

I can see that angular2-router-loader now processes all .ts files.

**Comment by brandonroberts** [comment]
Ok good. Thanks for digging into it
