### ISSUE TITLE
Cannot install v0.3.1

### ISSUE THREAD

**Issue by aloker** [brandonroberts/angular2-router-loader#7]
Currently, v0.3.1 can't be installed with npm.

`npm install angular2-router-loader -dd`

hangs when npm tries to fetch tgz archive.

```
...
npm info retry fetch attempt 1 at 12:41:57
npm info attempt registry request try #1 at 12:41:57
npm http fetch GET https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
npm http fetch 504 https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
npm info retry will retry, error on last attempt: Error: server error 504
npm info attempt registry request try #2 at 12:42:57
npm http fetch GET https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
[    ..............] - loadRequestedDeps: http fetch GET https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
```

I tried to manually download https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz and get this error:

```
{"code":"InternalError","message":"Cannot read property '0.3.1' of undefined"}
```

For comparison, downloading version 0.2.2 (https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.2.2.tgz) works flawlessly.

I don't know if the error is on npm's end or if something went wrong during deployment of angular2-router-loader.

**Comment by joaogarin** [comment]
I am also getting these 504 errors

**Comment by RatnikovM** [comment]
I have the same problem.

**Comment by brandonroberts** [comment]
Must have been something wrong with npm when I published. I wish publish another patch release today.

**Comment by joaogarin** [comment]
btw wanted to ask, is this the solution that is currently being used with the CLI? Or is there another module doing the same do you know?

**Comment by dhardtke** [comment]
https://github.com/Quramy/angular2-load-children-loader

**Comment by brandonroberts** [comment]
@joaogarin the CLI uses a better approach than this loader, and its bundled into the AoTPlugin https://github.com/angular/angular-cli/tree/master/packages/webpack

**Comment by brandonroberts** [comment]
Version `0.3.2` has been published that should fix the 404 issues
