### ISSUE TITLE
npm Version 0.3.2?

### ISSUE THREAD

**Issue by Martin-Wegner** [brandonroberts/angular2-router-loader#8]
In github the latest release is `0.3.1` and the commits also end in `0.3.1` but in npm the latest release is `0.3.2`, what is going on here? Thanks in advance for clarification! I think you should pay heed to https://github.com/brandonroberts/angular2-router-loader/issues/5

**Comment by brandonroberts** [comment]
The npm version is `0.3.2` due to an issue with npm during the last release. There are no changes between `0.3.1` and `0.3.2`. I am going to add a changelog soon.
