### ISSUE TITLE
Using relative paths to app directory: how?

### ISSUE THREAD

**Issue by dhardtke** [brandonroberts/angular2-router-loader#9]
I am working on a project where I'd like to use both SystemJS (for dev) and webpack (for prod).

This is how my structure looks like
**app\app-routing.module.ts**
```js
// ...
{
    path: "admin",
    loadChildren: "app/admin/admin.module#AdminModule",
}
```
**app\admin\admin-routing.module.ts**
```js
// ...
{
    path: "",
    loadChildren: "app/admin/admin.overview.module#AdminOverviewModule",
    canActivate: [AuthGuard]
}
```

This works perfectly using **SystemJS**, but when I try to use your loader it results in:
```
[angular2-router-loader]: File: app\app-routing.module.ts
[angular2-router-loader]: Original: loadChildren: "app/admin/admin.module#AdminModule"
[angular2-router-loader]: Replacement: loadChildren: () => System.import('.\\..\\app\\admin\\admin.module.ngfactory')  .then(function(module) {    return module['AdminModuleNgFactory'];  })
 13% building modules 29/93 modules 64 active ...catalogues\my-catalogues.component.tsModuleNotFoundError: Module not found: Error: Can't resolve '.\app\admin\admin.overview.module.ngfactory' in 'compiled\app\admin'
```

I know I can get it working in **webpack** when using relative paths to the module (by removing `app/admin/` from admin-routing.module.ts), but then it won't work in SystemJS.

Is there a way I can get it working in both (without nasty workarounds like replacing `app/admin/` manually as preLoader in the webpack config)?

UPDATE:
Trying to use the `string-replace-loader` didn't even work 😃

**Comment by dhardtke** [comment]
Is there a way to teach the loader to use absolute paths (to the app dir, like I've shown in my issue post) and make the loader convert them into "module-relative" paths?

Didn't find a way to do it... yet

**Comment by dhardtke** [comment]
Thanks for the suggestion. I am probably going to do that.

Maybe it will all work fine when the AotPlugin works with loadChildren - I mean, when it works properly. Right now it does result in separated js chunks being generated but they won't load properly (in the browser).

**Comment by dhardtke** [comment]
Okay, after a few hours of trying I have to give up. I did not find a way (even using a custom loader) to use paths relative to the modules (like it is for components) with SystemJS or the other approach, using app-relative paths for webpack.

**Comment by brandonroberts** [comment]
Is there a specific reason you're using SystemJS for dev and webpack for prod?

**Comment by dhardtke** [comment]
Yes. I don't want to have the webpack-dev-server running in the background while developing since in my opinion that could slow me down.

**Comment by dhardtke** [comment]
For now I found a workaround by using
`loadChildren: (window["System"] ? "app/admin/" : "") + "admin.overview.module#AdminOverviewModule",`

but I will try the webpack-dev-server to see how it works using that one.

**Comment by dhardtke** [comment]
Oh, and another reason why I don't want to use the webpack-dev-server is that I have Tomcat running on port 8080 to serve my application. It would complicate things a lot if I would have to set up a different port.

**Comment by dhardtke** [comment]
Okay, you're right - using `webpack-dev-server` is the best choice here.

Thanks pal!

**Comment by jayoungers** [comment]
How did you get your chunks to load correctly with webpack-dev-server running on another port?  Every time I try to hit a lazy loaded path locally it tries to lookup the chunk file on the primary web server port opposed to the port webpack is running on

**Comment by dhardtke** [comment]
What do you mean? I have a Tomcat Web Server running in the background, but I am accessing my application from Port 8081, where the webpack-dev-server is running.

Can you get into more detail pls?

**Comment by jayoungers** [comment]
That might be my issue; I'm running it in reverse from that.

I have my application running at `http://localhost:53455`, and in my index file, I'm referencing my bundle from webpack-dev-server like so:
`<script src="http://localhost:9000/main.bundle.js"></script>`

Everything works great until it needs to request a chunk from a lazy loaded route, which it attempts to grab from `http://localhost:53455/0.chunk.js` opposed to `http://localhost:9000/0.chunk.js`

Maybe I'll just look into reversing that flow and using the proxy api settings

**Comment by jayoungers** [comment]
Nevermind - my issue was I was setting the publicPath at the devServer level, not at the output level

**Comment by vvolodin** [comment]
@jayoungers Could you please elaborate on how exactly you fixed your issue? I'm having the same. I need to serve my files from /build/ on production, but I'm using webpack-dev-server with publicPath=https://localhost:8080/build/ while developing, and angular-router-loader references /build/0.chunk.js without localhost:8080 bit.

**Comment by jayoungers** [comment]
We've since switched to angular-cli, so I can't remember 100%, but based on the comment it looks like I just had the 'publicPath' property setup in the wrong place in the config: it should be in the `output: { } `section
